on:
  push:
    branches: 
      - master

jobs:
  ci_cd_compositon:
    name: CI/CD COMPOSITION
    runs-on: ubuntu-latest
    steps:
      - uses: ./codeql.yml
      - uses: ./node.js.yml
      - uses: ./npm-publish.yml
