permissions: read-all

on:
  push:
    branches: 
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  analyze:
    uses: ./.github/workflows/codeql.yml
    needs: checkout
    permissions: 
      security-events: write
      packages: read
      actions: read
      contents: read
  build:
    needs: analyze
    uses: ./.github/workflows/node.js.yml
  publish:
    needs: build
    uses: ./.github/workflows/npm-publish.yml
      
