permissions: read-all

on:
  push:
    branches: 
      - master

jobs:
  analyze:
    uses: ./.github/workflows/codeql.yml
    permissions: 
      security-events: write
      packages: read
      actions: read
      contents: read
  build and test:
    needs: analyze
    uses: ./.github/workflows/node.js.yml
  npm_publish:
    needs: build
    uses: ./.github/workflows/publish.yml
      
