permissions: read-all

on:
  push:
    branches:
      - master

jobs:
  analyze:
    uses: ./.github/workflows/codeql.yml
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
  build-and-test:
    needs: analyze
    uses: ./.github/workflows/node.js.yml
  publish:
    permissions: write-all
    needs: build-and-test
    uses: ./.github/workflows/publish.yml
    secrets:
      npm_token: ${{secrets.NPM_TOKEN}}
