permissions: read-all

on:
  push:
    branches: 
      - master

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  codeql:
    uses: ./.github/workflows/codeql.yml
  build:
    uses: ./.github/workflows/node.js.yml
  publish:
    uses: ./.github/workflows/npm-publish.yml
      
